#pragma once

// Icon shown on the review and home screens. The glyph symbol is generated by
// the SDK from the icon file declared in the Makefile (ICON_NANOSP / ICON_NANOX).
#define ICON_APP_KOKUIN C_kokuin_app_14px

/**
 * Present the sign-message review flow and defer signing to the user's approval.
 *
 * Approving runs the signature; rejecting discards the message. Either outcome
 * sends the APDU response, so the caller must not send a status word itself.
 */
void ui_display_sign(void);

/**
 * Present the key-agreement review flow and defer the ECDH computation to the
 * user's approval.
 *
 * Approving runs the key agreement and returns the shared secret; rejecting
 * discards the ephemeral key. Either outcome sends the APDU response, so the
 * caller must not send a status word itself.
 */
void ui_display_ecdh(void);
